stages:
  - build

build_image:
  stage: build
  image: docker:git
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.scpio.net
  - docker login -u ${DOCKER_HUB_USER} -p '${DOCKER_HUB_TOKEN}'
  - docker build -t registry.scpio.net/open-source/asterisk:${CI_COMMIT_REF_SLUG} -t scorpioint/asterisk ./asterisk
  - docker push registry.scpio.net/open-source/asterisk:${CI_COMMIT_REF_SLUG}
  - docker push scorpioint/asterisk
  only:
  - master

